public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.5;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        dog = dog + 4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var MOneBoxer = 78.2;
        var MTwoBoxer = 82.7;
        var MBoxers = MOneBoxer + MTwoBoxer;
        System.out.println("Общий вес боксеров " + MBoxers + " кг");
        var difference = MTwoBoxer - MOneBoxer;
        System.out.println("Второй боксер весит на " + difference + " кг больше первого");
        var remainder = (MOneBoxer + MTwoBoxer) % MOneBoxer;
        System.out.println("разница в весе двух боксеров составляет " + remainder + " кг");
        var tWork = 640;
        var time = 8;
        var people = tWork / time;
        System.out.println("Всего работников в компании " + people + " человек");
        people = people + 94;
        tWork = time * people;
        System.out.println("Если в компании работает " + people + " человек, то всего " + tWork + " часов работы поделено между сотрудниками");
        byte pen = 1;
        System.out.println("Значение переменной с типом byte равно " + pen);
        short apple = 10;
        System.out.println("Значение переменной с типом sort равно " + apple + "");
        int flat = 100;
        System.out.println("Значение переменной с типом int равно " + flat + "");
        long km = 1000L;
        System.out.println("Значение переменной с типом long равно " + km + "");
        float m = 33.5F;
        System.out.println("Значение переменной с типом float равно " + m + "");
        double kg = 27.524;
        System.out.println("Значение переменной с типом double равно " + kg + "");
        float a = 27.12f;
        long b = 987678965549L;
        float c = 2.786f;
        short d = 569;
        short e = -159;
        short f = 27897;
        byte g = 67;
        byte LP = 23;
        byte AS = 27;
        byte EA = 30;
        short p = 480;
        int list = p / (LP + AS + EA);
        System.out.println("На каждого ученика рассчитано " + list + " листов бумаги");
        double BMin = 16 / 2;
        double BMinOneTime = BMin * 10;
        System.out.println("За 20 минут машина произвела " + BMinOneTime + " бутылок");
        double BMinTowTime = BMinOneTime * 3 * 24;
        System.out.println("В сутки машина произвела " + BMinTowTime + " бутылок");
        double BMinTreeTime = BMinTowTime * 3;
        System.out.println("За трое суток машина произвела" + BMinTreeTime + " бутылок");
        double BMinFourTime = BMinTowTime * 30;
        System.out.println("За месяц машина произвела " + BMinFourTime+ " бутылок");
    }
}